### ISSUE TITLE
StructureSimilarity.compute_lrmsd_fast() and StructureSimilarity.compute_lrmsd_fast() provide different results

### ISSUE THREAD

**Issue by DarioMarzella** [DeepRank/pdb2sql#57]
**Describe the bug**
In a case where the model and the reference file cannot be easily aligned, StructureSimilarity.compute_lrmsd_fast() and StructureSimilarity.comp

ute_lrmsd_fast() provide different results (respectively, 0.837 and 3.38)

**Environment:**
- OS system: Linux
- Version: CentOS Linux 7 (Core)
- Branch commit ID: 7a6d7cda0b90a11c14d5237ad5c5a0a7c2acbb9d
- Inputs: `python get_rmsd.py` (in the attached folder)

**To Reproduce**
Steps/commands to reproduce the behaviour:
 1.  open the attached folder named `different_lrmsd`
 2. run `python get_rmsd.py`

**Expected Results**
StructureSimilarity.compute_lrmsd_fast() and StructureSimilarity.compute_lrmsd_pdb2sql() should be providing the same output CA l-RMSD.  

**Actual Results or Error Info**
The two methods provide very different CA l-RMSDs (respectively, 0.837 and 3.38)

**Additional Context**
A .pse PyMol session is included in the attached folder. It is possible to see how the `_model` is technically very similar to the `ref` file, but they are not properly aligned by PyMol. 
StructureSimilarity.compute_lrmsd_pdb2sql() as well is probably failing in aligning them, but StructureSimilarity.compute_lrmsd_fast() seems to work properly.

[different_lrmsd.zip](https://github.com/DeepRank/pdb2sql/files/4752205/different_lrmsd.zip)

**Comment by DTRademaker** [comment]
Dear Dario,

I could not reproduce your problem because of an error "Residue numbering not identical in ref and decoy". After renumbering the 'ref.pdb' so that it had the same numbering as 'model.pdb' (see atachement) it gave very similar results for the two similarity methods: "l-RMSD fast:  3.414  l-RMSD pdb2sql:  3.38".
Maybe update your pdb2sql library or just try to restart your pc? (based on that you did not get the same error as I did)

hope it helps,
Daniel
[different_lrmsd.zip](https://github.com/DeepRank/pdb2sql/files/7920552/different_lrmsd.zip)
